parent: avo
name: avoChild2
display_name: avhoChild2
version: 1.0.0
meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column
    layout-static-pages:
      name: StaticPages
      description: PRGRM Custom static pages layout

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
    BLOCKSPECIALS_SPECIALS_NBR: 1
  modules:
   to_enable:
     - ps_linklist
     - ps_facetedsearch
     - ps_featuredproducts
     - ps_contactinfo
   to_disable:
     - ps_imageslider
     - ps_mainmenu
     - ps_customtext
     - ps_customeraccountlinks
  hooks:
    modules_to_hook:
      displayHeader:
        - ps_searchbar
        - ps_shoppingcart
        - owlcustomhtml
        - owlslideshow
        - owlthemeconfigurator
        - owlblog
        - owlmegamenu
        - owlblockwishlist
        - owlrightsidebar
        - owlproductcomments
        - owlproductfilter
        - owlcountdown
        - owlcouponpop
      displayNav1:
        - ps_currencyselector
        - owlmegamenu
        - ps_customersignin
        - ps_languageselector
        - ps_shoppingcart
      displayTop:
        - owlcustomhtml
        - owlproductfilter
        - ps_specials
      displayNavFullWidth:
        - owlslideshow
      displayHome:
        - owlproductfilter
      displayTopHome:
        - owlcustomhtml
      displayMiddleHome:
        - owlblog
        - ps_banner
      displayBottomHome:
        - owlbloglatestnews
      displayFooterBefore:
        - owlcustomhtml
      displayFooter:
        - owlcustomhtml
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
      displayFooterAfter:
        - owlcustomhtml
      displayCountDownProduct:
        - owlcountdown
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
        - ps_bestsellers
        - owlblog
        - ps_advertising
      displaySearch:
        - ps_searchbar
      displayProductButtons:
        - ps_sharebuttons
      displayReassurance:
        - blockreassurance
      actionShopDataDuplication:
        - owlblog
        - owlslideshow
        - owlcustomhtml
      actionObjectLanguageAddAfter:
        - owlslideshow
        - owlcustomhtml
      displayMyAccountBlock:
       - owlblockwishlist
      displayCustomerAccount:
       - owlblockwishlist
      displayProductDetailReviews:
       - owlproductcomments
      displayProductListReviews:
       - owlproductcomments
      displayProductAdditionalInfo:
        - ps_sharebuttons
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayCrossSellingShoppingCart:
        - ps_featuredproducts
      displayOwlFooter:
        - owlcouponpop
        - owluecookie
        - owlrightsidebar
      displayPageTitle:
        - owlpagetitle
      owlProductTab:
        - owlsizeguide
        - owlproductcomments
      owlProductTabContent:
        - owlsizeguide
        - owlproductcomments
  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 100
      height: 100
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 210
      height: 210
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 300
      height: 300
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 960
      height: 423
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
    search: layout-left-column
dependencies:
  modules:
    - owlmegamenu
    - owlthemeconfigurator
    - owlslideshow
    - owlcustomhtml
    - owlblog
    - owlbloglatestnews
    - owlcouponpop
    - owluecookie
    - owlpagetitle
    - owlrightsidebar
    - owlsizeguide
    - owlblockwishlist
    - owlproductcomments
    - owlcompare
    - owlproductfilter
    - owlcountdown
    - ps_specials
